<?php

/**
 * Implements hook_markdown_parser_info_alter().
 *
 * This replaces the 'league/commonmark' plug-in class with our own.
 *
 * @param array $info
 *   An array of markdown parser plugin definitions, as collected by the
 *   plugin annotation discovery mechanism.
 *
 * @see \Drupal\omnipedia_content\Plugin\Markdown\CommonMark\CommonMark
 *   The 'league/commonmark' class that we provide.
 */
function omnipedia_content_markdown_parser_info_alter(array &$info) {
  $info['league/commonmark']['class'] =
    'Drupal\\omnipedia_content\\Plugin\\Markdown\\CommonMark\\CommonMark';
  $info['league/commonmark']['provider'] = 'omnipedia_content';
}
