<?php

declare(strict_types=1);

/**
 * Clear cached filter plug-in output for MarkdownAttachmentsFilter.
 */
function omnipedia_content_update_10601(): void {

  // Clearing all render caching works for our purposes but it's fairly
  // heavy-handed. A more elegant version of this could loop through all filter
  // formats, passing their 'config:filter.format.*' cache tags to the
  // invalidator if said format has the 'omnipedia_markdown_attachments' filter
  // enabled.
  \Drupal::service('cache_tags.invalidator')->invalidateTags(['rendered']);

}

/**
 * Rebuild container and libraries for 6.x to 7.x upgrade.
 */
function omnipedia_content_update_10701(): void {

  \Drupal::service('kernel')->invalidateContainer();

  \Drupal::service('library.discovery')->clearCachedDefinitions();

}

/**
 * Clear cached attached data output to enable abbreviations everywhere.
 */
function omnipedia_content_update_10702(): void {

  \Drupal::service('cache_tags.invalidator')->invalidateTags([
    'omnipedia_attached_data_list',
  ]);

}

/**
 * Invalidate cache tags for infobox media view mode addition.
 */
function omnipedia_content_update_10703(): void {

  // We don't currently have a cache tag for specific elements.
  \Drupal::service('cache_tags.invalidator')->invalidateTags([
    'media_view',
  ]);

}

/**
 * Invalidate cache tags for disabling infobox media view mode.
 */
function omnipedia_content_update_10704(): void {

  // We don't currently have a cache tag for specific elements.
  \Drupal::service('cache_tags.invalidator')->invalidateTags([
    'media_view',
  ]);

}

/**
 * Invalidate 'rendered' cache tag for addition of 'omnipedia_element' tag.
 */
function omnipedia_content_update_10705(): void {

  \Drupal::service('cache_tags.invalidator')->invalidateTags([
    'rendered',
  ]);

}

/**
 * Rebuild container for element plug-in manager constructor changes.
 */
function omnipedia_content_update_10706(): void {

  \Drupal::service('kernel')->invalidateContainer();

}

/**
 * Rebuild libraries (and thus components) and element plug-ins for pitch.
 */
function omnipedia_content_update_10707(): void {

  \Drupal::service('library.discovery')->clearCachedDefinitions();

  \Drupal::service(
    'plugin.manager.omnipedia_element',
  )->clearCachedDefinitions();

}

/**
 * Rebuild element plug-ins for <pitch-highlight> element.
 */
function omnipedia_content_update_10708(): void {

  \Drupal::service(
    'plugin.manager.omnipedia_element',
  )->clearCachedDefinitions();

}

/**
 * Rebuild element plug-ins for moving pitch elements to separate module.
 */
function omnipedia_content_update_10709(): void {

  \Drupal::service(
    'plugin.manager.omnipedia_element',
  )->clearCachedDefinitions();

}

/**
 * Rebuild container for addition of autowire interface service aliases.
 */
function omnipedia_content_update_10710(): void {

  \Drupal::service('kernel')->invalidateContainer();

}
/**
 * Clear cached block definitions for addition of table of contents block.
 */
function omnipedia_content_update_10711(): void {

  \Drupal::service('plugin.manager.block')->clearCachedDefinitions();

}
