<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * This provides the help block contents for the 'entity.node.omnipedia_changes'
 * route.
 */
function omnipedia_content_changes_help(
  $routeName, RouteMatchInterface $routeMatch
) {

  if ($routeName === 'entity.node.omnipedia_changes') {
    /** @var string */
    $baseClass = 'omnipedia-changes-help';

    return ['omnipedia_changes_help'  => [
      '#type'       => 'container',
      '#attributes' => ['class' => [$baseClass]],

      'description' => [
        '#type'   => 'html_tag',
        '#tag'    => 'p',
        '#value'  => \t('This displays additions, deletions, and changes to the current page compared to the previous version, using the following indicators:'),
        '#attributes'   => ['class' => [$baseClass . '__description']],
      ],

      'legend'  => [
        '#theme'        => 'item_list',
        '#list_type'    => 'ul',
        '#items'        => [
          'added' => [
            '#type'   => 'html_tag',
            '#tag'    => 'ins',
            '#value'  => \t('Added'),
            '#wrapper_attributes'   => ['class' => [
              $baseClass . '__legend-item',
              $baseClass . '__legend-item--added',
            ]],
            '#attributes'   => ['class' => [
              $baseClass . '__diff',
              $baseClass . '__diff--added',
            ]],
          ],
          'removed' => [
            '#type'   => 'html_tag',
            '#tag'    => 'del',
            '#value'  => \t('Deleted'),
            '#wrapper_attributes'   => ['class' => [
              $baseClass . '__legend-item',
              $baseClass . '__legend-item--removed',
            ]],
            '#attributes'   => ['class' => [
              $baseClass . '__diff',
              $baseClass . '__diff--removed',
            ]],
          ],
          'changed' => [
            '#type'   => 'html_tag',
            '#tag'    => 'span',
            '#value'  => \t('Changed'),
            '#wrapper_attributes'   => ['class' => [
              $baseClass . '__legend-item',
              $baseClass . '__legend-item--changed',
            ]],
            '#attributes'   => ['class' => [
              $baseClass . '__diff',
              $baseClass . '__diff--changed',
            ]],
          ],
        ],
        '#attributes'   => ['class' => [
          $baseClass . '__legend',
          'unlisted-list',
        ]],
      ],

      '#attached'   => [
        'library'     => ['omnipedia_content_changes/component.changes'],
      ],
   ]];
  }

}
